require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });
const pool = require('../config/db');

const allQuestions = [
  // --- DSA: ARRAYS (Topic 1) ---
  { topic_id: 1, subtopic: 'Two Pointers', question_text: 'Which of the following problems is best solved using a two-pointer approach on a sorted array?', option_a: 'Finding the maximum element', option_b: 'Finding a pair with a given sum', option_c: 'Reversing the array', option_d: 'Finding the sum of all elements', correct_option: 'b', difficulty: 2, concept_tested: 'Two Pointers on sorted arrays', explanation: 'Two pointers can efficiently find pairs in a sorted array by moving endpoints towards the center without nested loops.', prerequisite_concept: 'Iteration' },
  { topic_id: 1, subtopic: 'Prefix Sum', question_text: 'What is the primary advantage of a prefix sum array?', option_a: 'It sorts the array in O(n) time.', option_b: 'It allows O(1) time complexity for range sum queries.', option_c: 'It reduces the space complexity of the array.', option_d: 'It automatically balances a binary search tree.', correct_option: 'b', difficulty: 2, concept_tested: 'Prefix Sum advantages', explanation: 'Prefix sums precompute cumulative totals, allowing any contiguous subsegment sum to be queried in constant time O(1).', prerequisite_concept: 'Iteration' },
  { topic_id: 1, subtopic: "Kadane's Algorithm", question_text: "What is the time complexity of Kadane's Algorithm for finding the maximum subarray sum?", option_a: 'O(n^2)', option_b: 'O(n log n)', option_c: 'O(n)', option_d: 'O(1)', correct_option: 'c', difficulty: 3, concept_tested: "Kadane's time complexity", explanation: "Kadane's algorithm processes the array linearly, comparing sums in a single O(n) pass.", prerequisite_concept: 'Dynamic Programming basics' },
  { topic_id: 1, subtopic: 'Sorting Tricks', question_text: 'Which sorting algorithm is heavily utilized as a preliminary step before returning the majority element in O(1) space?', option_a: 'Counting Sort', option_b: 'Merge Sort', option_c: 'Quick Sort', option_d: 'Boyer-Moore Voting', correct_option: 'd', difficulty: 4, concept_tested: 'Boyer-Moore Voting conceptualization', explanation: 'While sorting takes O(n log n), Boyer-Moore finds the majority element in O(n) time and O(1) space directly without sorting.', prerequisite_concept: 'Array traversing' },
  { topic_id: 1, subtopic: 'Sliding Window Basics', question_text: 'When tracking the maximum sum of contiguous subarrays of size K, how do you adjust the sum when moving the window?', option_a: 'Recalculate the entire sum.', option_b: 'Subtract the element leaving the window and add the new element.', option_c: 'Multiply the array elements.', option_d: 'Use a hashmap to store overlapping elements.', correct_option: 'b', difficulty: 1, concept_tested: 'Fixed window shifting', explanation: 'Moving a fixed window right means discarding the outgoing left element and adding the incoming right element.', prerequisite_concept: 'Prefix Sum' },

  // --- DSA: SLIDING WINDOW (Topic 2) ---
  { topic_id: 2, subtopic: 'Variable Window', question_text: "When solving 'Longest Substring Without Repeating Characters', what happens to the left pointer when a duplicate is found?", option_a: 'It resets to the beginning.', option_b: 'It stays in place until the right pointer finishes.', option_c: 'It moves right until the duplicate is no longer in the window.', option_d: 'It swaps places with the right pointer.', correct_option: 'c', difficulty: 3, concept_tested: 'Variable Sliding Window mechanic', explanation: 'The left pointer shrinks the window from the left just enough to remove the violation (the duplicate character).', prerequisite_concept: 'Fixed Window' },
  { topic_id: 2, subtopic: 'String Window Problems', question_text: 'Which data structure is typically paired with a sliding window to efficiently track character frequencies?', option_a: 'Stack', option_b: 'Queue', option_c: 'Hash Map / Frequency Array', option_d: 'Binary Search Tree', correct_option: 'c', difficulty: 2, concept_tested: 'Frequency mapping', explanation: 'A Hash Map or an integer array of size 26/256 allows O(1) lookups and updates for character frequencies inside the window.', prerequisite_concept: 'Hash Maps' },
  { topic_id: 2, subtopic: 'Minimum Window Substring', question_text: 'In the Minimum Window Substring problem, when do you move the right pointer vs the left pointer?', option_a: 'Right when window is valid, left otherwise.', option_b: 'Left when window is invalid, right otherwise.', option_c: 'Right to expand until the window is valid, then left to shrink while it remains valid.', option_d: 'Both pointers always move together.', correct_option: 'c', difficulty: 4, concept_tested: 'Minimum Window Substring logic', explanation: 'Expand right until you have all required characters, then shrink from left to minimize the window while maintaining validity.', prerequisite_concept: 'Frequency mapping' },
  { topic_id: 2, subtopic: 'Fruit Into Baskets', question_text: "'Fruit Into Baskets' (at most 2 distinct values in window) is a direct variant of which classic problem?", option_a: 'Minimum Window Substring', option_b: 'Longest Substring With At Most K Distinct Characters', option_c: 'Longest Subarray with Sum K', option_d: 'Fixed Window Maximum', correct_option: 'b', difficulty: 3, concept_tested: 'K Distinct Characters pattern', explanation: 'Fruit Into Baskets is exactly the K-distinct sliding window pattern with K=2.', prerequisite_concept: 'Variable Sliding Window mechanic' },
  { topic_id: 2, subtopic: 'Longest Repeating Character Replacement', question_text: "In 'Longest Repeating Character Replacement' with at most K replacements, what condition validates the window?", option_a: 'window_length - max_frequency <= K', option_b: 'window_length - K >= max_frequency', option_c: 'max_frequency + K >= window_length', option_d: 'K >= window_length', correct_option: 'a', difficulty: 4, concept_tested: 'Character replacement window validity', explanation: 'If (window_size - count of most frequent char) <= K, we can replace all other chars to make all uniform.', prerequisite_concept: 'Frequency mapping' },
  { topic_id: 2, subtopic: 'Subarray Sum Problems', question_text: 'When finding subarrays with sum exactly equal to K with negative numbers, what additional structure is required over a simple sliding window?', option_a: 'Monotonic Stack', option_b: 'Prefix Sum + Hash Map', option_c: 'Deque', option_d: 'Segment Tree', correct_option: 'b', difficulty: 4, concept_tested: 'Prefix sum for subarray count', explanation: 'Sliding window only works for non-negative numbers. For arbitrary integers, prefix sum + hashmap solves subarray-sum-equals-K in O(n).', prerequisite_concept: 'Variable Sliding Window mechanic' },
  { topic_id: 2, subtopic: 'Fixed Window', question_text: 'In a fixed-size window of size K, what is the time complexity of finding the maximum using a Monotonic Deque?', option_a: 'O(n^2)', option_b: 'O(n log n)', option_c: 'O(n)', option_d: 'O(K*n)', correct_option: 'c', difficulty: 3, concept_tested: 'Monotonic Deque for Window Maximum', explanation: 'A monotonic deque ensures each element is pushed and popped at most once, making the overall algorithm O(n).', prerequisite_concept: 'Fixed Window' },
  { topic_id: 2, subtopic: 'Sliding Window Patterns', question_text: 'Which of the following problems CANNOT be solved efficiently with a standard sliding window alone?', option_a: 'Maximum sum subarray of size K', option_b: 'Smallest subarray with sum >= S (positive numbers)', option_c: 'Number of subarrays with product less than K', option_d: 'Median of sliding window', correct_option: 'd', difficulty: 5, concept_tested: 'Sliding window limitations', explanation: 'Sliding window cannot maintain sorted order. Median in a sliding window requires two heaps, not a simple window.', prerequisite_concept: 'Monotonic Deque for Window Maximum' },
  { topic_id: 2, subtopic: 'Two Pointer vs Sliding Window', question_text: 'What best distinguishes a Two Pointer approach from a Sliding Window approach?', option_a: 'Two pointers always move in the same direction.', option_b: 'Sliding window always has a fixed size.', option_c: 'Two pointers can move in opposite or same direction; sliding window specifically tracks a contiguous subarray.', option_d: 'There is no difference between the two techniques.', correct_option: 'c', difficulty: 2, concept_tested: 'Two Pointers vs Sliding Window distinction', explanation: 'Sliding window is essentially a same-direction two-pointer technique focused specifically on contiguous subarrays/substrings.', prerequisite_concept: 'Fixed Window' },
  { topic_id: 2, subtopic: 'Kadane Variant', question_text: "Kadane's Algorithm can be viewed as which type of sliding window technique?", option_a: 'Fixed Window of size K', option_b: 'Shrinking-only window', option_c: 'Variable window that resets when the running sum goes negative', option_d: 'Queue-based sliding window', correct_option: 'c', difficulty: 3, concept_tested: 'Kadane as Sliding Window', explanation: "Kadane's resets the window start whenever the running prefix sum becomes negative — choosing to start fresh, like a variable sliding window reset.", prerequisite_concept: 'Variable Sliding Window mechanic' },

  // --- DSA: BINARY SEARCH (Topic 3) ---
  { topic_id: 3, subtopic: 'Classic Binary Search', question_text: 'Which condition must be true to apply standard binary search?', option_a: 'The elements must be integers.', option_b: 'The collection must be sorted.', option_c: 'The collection must not contain duplicates.', option_d: 'The length must be a power of 2.', correct_option: 'b', difficulty: 1, concept_tested: 'Binary Search prerequisites', explanation: 'Binary search relies on a sorted domain to recursively divide the search space by half.', prerequisite_concept: 'Iteration' },
  { topic_id: 3, subtopic: 'Search Space Reduction', question_text: 'If low=0 and high=arr.length-1, which formula safely calculates the middle index without integer overflow?', option_a: '(low + high) / 2', option_b: 'low + (high - low) / 2', option_c: '(low ^ high) >> 1', option_d: 'high - (low / 2)', correct_option: 'b', difficulty: 2, concept_tested: 'Integer overflow in binary search', explanation: 'low + (high - low) / 2 avoids the potential overflow that (low + high) would cause if both values are very large.', prerequisite_concept: 'Classic Binary Search' },
  { topic_id: 3, subtopic: 'Binary Search on Answer', question_text: "When applying Binary Search on Answer for the 'Allocate Minimum Pages' problem, what represents the search space?", option_a: 'The indices of the book array.', option_b: 'The number of students.', option_c: 'The range from the max pages in a single book to the sum of all pages.', option_d: 'The number of books.', correct_option: 'c', difficulty: 5, concept_tested: 'Defining BS search space', explanation: 'The answer must be at least the largest single book and at most the sum of all books if one student reads everything.', prerequisite_concept: 'Search Space Reduction' },

  // --- DSA: DYNAMIC PROGRAMMING (Topic 4) ---
  { topic_id: 4, subtopic: 'Memoization', question_text: 'What is the core difference between memoization and tabulation in DP?', option_a: 'Memoization is bottom-up; tabulation is top-down.', option_b: 'Memoization reduces time complexity more than tabulation.', option_c: 'Memoization is top-down (recursive); tabulation is bottom-up (iterative).', option_d: 'There is no difference.', correct_option: 'c', difficulty: 2, concept_tested: 'Memoization vs Tabulation', explanation: 'Memoization caches recursive call results (top-down). Tabulation builds solutions iteratively from base cases (bottom-up).', prerequisite_concept: 'Recursion' },
  { topic_id: 4, subtopic: 'Knapsack', question_text: "In the 0/1 Knapsack problem, what does '0/1' signify?", option_a: 'Items can only weigh 0 or 1.', option_b: 'The answer is always a boolean 0 or 1.', option_c: 'An item must be either fully taken (1) or fully left behind (0).', option_d: 'Only problems with 0 or 1 items are solved.', correct_option: 'c', difficulty: 3, concept_tested: '0/1 Knapsack constraints', explanation: 'You cannot take fractional amounts of an item. It is a discrete choice of inclusion (1) or exclusion (0).', prerequisite_concept: '2D DP' },
  { topic_id: 4, subtopic: 'Longest Common Subsequence', question_text: 'What are the time and space complexities of the classic LCS DP solution for strings of length m and n?', option_a: 'O(m+n) time and O(1) space', option_b: 'O(m*n) time and O(m*n) space', option_c: 'O(m*n) time and O(min(m,n)) space', option_d: 'O(m^2*n^2) time', correct_option: 'b', difficulty: 3, concept_tested: 'LCS complexity', explanation: 'LCS fills an m×n DP table where each cell depends on the cell above, left, and diagonally above-left. Both time and space are O(m*n).', prerequisite_concept: '2D DP' },
  { topic_id: 4, subtopic: 'Longest Increasing Subsequence', question_text: 'What is the best possible time complexity for finding the Length of the Longest Increasing Subsequence (LIS)?', option_a: 'O(n!)', option_b: 'O(n^2)', option_c: 'O(n log n)', option_d: 'O(n)', correct_option: 'c', difficulty: 4, concept_tested: 'LIS optimal algorithm', explanation: 'The patience sorting / binary search approach achieves O(n log n) by maintaining a tails array and using binary search to find insertion positions.', prerequisite_concept: 'Memoization vs Tabulation' },
  { topic_id: 4, subtopic: 'Coin Change', question_text: 'In the Coin Change problem (minimum coins), which DP transition correctly builds the answer?', option_a: 'dp[i] = dp[i - 1] + 1 for each coin', option_b: 'dp[i] = min(dp[i], dp[i - coin] + 1) for each coin where coin <= i', option_c: 'dp[i] = max(dp[i], dp[i - coin]) for each coin', option_d: 'dp[i] = dp[i - coin] * coin for each denomination', correct_option: 'b', difficulty: 3, concept_tested: 'Coin Change DP transition', explanation: 'For each amount i and each coin denomination, if we use that coin, minimum coins = dp[i-coin]+1. We take the minimum across all valid coins.', prerequisite_concept: 'Memoization vs Tabulation' },
  { topic_id: 4, subtopic: 'Partition DP', question_text: "What property must an array have for the 'Partition Equal Subset Sum' problem to have a solution?", option_a: 'The length must be even.', option_b: 'All elements must be positive.', option_c: 'The total sum must be even.', option_d: 'Elements must be sorted.', correct_option: 'c', difficulty: 3, concept_tested: 'Partition Equal Subset Sum feasibility', explanation: 'If total sum is odd it cannot be split into two equal halves. So total sum must be even; then find a subset with sum = total/2.', prerequisite_concept: '0/1 Knapsack constraints' },
  { topic_id: 4, subtopic: 'Edit Distance', question_text: 'Edit Distance between two strings allows which three operations at unit cost?', option_a: 'Insert, Delete, Swap', option_b: 'Insert, Delete, Replace', option_c: 'Rotate, Delete, Merge', option_d: 'Shift, Insert, Copy', correct_option: 'b', difficulty: 2, concept_tested: 'Edit Distance operations', explanation: 'Levenshtein Edit Distance counts the minimum Insert, Delete, and Replace operations to transform one string into another.', prerequisite_concept: 'LCS complexity' },
  { topic_id: 4, subtopic: 'Unbounded Knapsack', question_text: 'How does Unbounded Knapsack differ from 0/1 Knapsack in its DP recurrence?', option_a: 'Unbounded uses a 2D table; 0/1 uses a 1D table.', option_b: 'In Unbounded Knapsack the same item can be chosen multiple times — dp[i][w] uses dp[i][w-wt[i]] (same row) instead of dp[i-1][w-wt[i]].', option_c: 'Unbounded Knapsack requires sorting items by value.', option_d: 'There is no difference in recurrence.', correct_option: 'b', difficulty: 4, concept_tested: 'Unbounded Knapsack recurrence', explanation: 'In 0/1, after picking item i you use dp[i-1] (no reuse). In Unbounded, you still reference dp[i] (same item can be picked again).', prerequisite_concept: '0/1 Knapsack constraints' },
  { topic_id: 4, subtopic: 'DP on Trees', question_text: 'Which of the following is a classic example of DP on Trees?', option_a: 'Coin Change', option_b: 'Maximum Independent Set in a tree', option_c: 'Longest Common Subsequence', option_d: 'Matrix Chain Multiplication', correct_option: 'b', difficulty: 4, concept_tested: 'DP on Trees pattern', explanation: 'Maximum Independent Set on a tree uses post-order DFS DP: for each node, either include it (exclude children) or exclude it (take best of children).', prerequisite_concept: 'Memoization vs Tabulation' },
  { topic_id: 4, subtopic: 'Matrix Chain Multiplication', question_text: 'Matrix Chain Multiplication determines the optimal parenthesization to minimize what?', option_a: 'The sum of all matrix dimensions', option_b: 'The total number of matrix additions', option_c: 'The total number of scalar multiplications', option_d: 'The number of matrix transpose operations', correct_option: 'c', difficulty: 4, concept_tested: 'Matrix Chain Multiplication objective', explanation: 'MCM finds the optimal way to parenthesize matrix multiplications to minimize scalar (element-wise) multiplications, which varies dramatically based on grouping order.', prerequisite_concept: '2D DP' },

  // --- OS: PROCESSES & THREADS (Topic 5) ---
  { topic_id: 5, subtopic: 'Context Switching', question_text: 'Which of the following is typically NOT shared among threads of the same process?', option_a: 'Code section', option_b: 'Data section (Globals)', option_c: 'Open files', option_d: 'Stack and Registers', correct_option: 'd', difficulty: 2, concept_tested: 'Thread memory architecture', explanation: 'Threads share the process heap, globals, and code, but each requires its own execution stack and CPU register state.', prerequisite_concept: 'Thread vs Process' },
  { topic_id: 5, subtopic: 'Process States', question_text: 'If a process requests an I/O operation, which state does it transition to?', option_a: 'Ready', option_b: 'Running', option_c: 'Waiting / Blocked', option_d: 'Terminated', correct_option: 'c', difficulty: 1, concept_tested: 'Process State transitions', explanation: 'A running process moves to the Wait/Blocked state while waiting for I/O, allowing the CPU to execute other processes.', prerequisite_concept: 'Process basics' },

  // --- OS: CPU SCHEDULING (Topic 6) ---
  { topic_id: 6, subtopic: 'SJF', question_text: 'Shortest Job First (SJF) is theoretically optimal for which scheduling metric?', option_a: 'Maximum throughput', option_b: 'Minimum average waiting time', option_c: 'Maximum CPU utilization', option_d: 'Fairness among all processes', correct_option: 'b', difficulty: 3, concept_tested: 'SJF optimality', explanation: 'SJF moves short jobs ahead of long jobs, drastically reducing the time short jobs wait, yielding optimal average waiting times.', prerequisite_concept: 'Burst Time concepts' },
  { topic_id: 6, subtopic: 'Round Robin', question_text: 'What happens in Round Robin scheduling if the time quantum is set excessively large?', option_a: 'It behaves like Shortest Job First.', option_b: 'It causes high context switching overhead.', option_c: 'It degenerates into First-Come-First-Serve (FCFS).', option_d: 'It leads to immediate deadlocks.', correct_option: 'c', difficulty: 2, concept_tested: 'Time Quantum impact', explanation: 'If the quantum is large enough that every process finishes within one slice, the scheduler effectively operates as FCFS.', prerequisite_concept: 'Context Switching' },
  { topic_id: 6, subtopic: 'SJF Preemptive', question_text: 'What is the preemptive version of SJF called?', option_a: 'Priority Scheduling', option_b: 'Shortest Remaining Time First (SRTF)', option_c: 'Multilevel Queue', option_d: 'Round Robin', correct_option: 'b', difficulty: 2, concept_tested: 'SRTF Scheduling', explanation: 'SRTF is the preemptive form of SJF. If a new process arrives with a shorter burst time than the remaining time of the current process, it preempts the CPU.', prerequisite_concept: 'SJF optimality' },
  { topic_id: 6, subtopic: 'Priority Scheduling', question_text: 'What problem can arise in Priority Scheduling if low-priority processes are continuously preempted?', option_a: 'Thrashing', option_b: 'Deadlock', option_c: 'Starvation / Indefinite Blocking', option_d: 'Race condition', correct_option: 'c', difficulty: 3, concept_tested: 'Starvation in Scheduling', explanation: 'A low-priority process may wait indefinitely if high-priority processes keep arriving. This is solved by aging — gradually increasing the priority of waiting processes.', prerequisite_concept: 'SRTF Scheduling' },
  { topic_id: 6, subtopic: 'Gantt Chart', question_text: 'In FCFS scheduling, if processes P1(burst=24ms), P2(burst=3ms), P3(burst=3ms) arrive in that order, what is the average waiting time?', option_a: '17ms', option_b: '0ms', option_c: '27ms', option_d: '10ms', correct_option: 'a', difficulty: 3, concept_tested: 'FCFS waiting time calculation', explanation: 'P1 waits 0, P2 waits 24, P3 waits 27. Average = (0+24+27)/3 = 17ms. FCFS is unfair to short processes when a long one arrives first.', prerequisite_concept: 'Time Quantum impact' },

  // --- OS: DEADLOCKS (Topic 7) ---
  { topic_id: 7, subtopic: 'Necessary Conditions', question_text: "Which is NOT one of the 4 Coffman necessary conditions for deadlock?", option_a: 'Mutual Exclusion', option_b: 'Hold and Wait', option_c: 'Preemption', option_d: 'Circular Wait', correct_option: 'c', difficulty: 2, concept_tested: 'Deadlock conditions', explanation: 'The condition is NO Preemption. If resources can be preempted, deadlocks can often be resolved.', prerequisite_concept: 'Resource concepts' },
  { topic_id: 7, subtopic: "Banker's Algorithm", question_text: "What is the primary purpose of the Banker's Algorithm?", option_a: 'Deadlock Detection', option_b: 'Deadlock Avoidance', option_c: 'Deadlock Prevention', option_d: 'Deadlock Recovery', correct_option: 'b', difficulty: 4, concept_tested: "Banker's Algorithm purpose", explanation: "Banker's Algorithm is used for deadlock avoidance by simulating resource allocation to ensure the system remains in a safe state.", prerequisite_concept: 'Deadlock conditions' },

  // --- DBMS: NORMALIZATION (Topic 8) ---
  { topic_id: 8, subtopic: 'BCNF', question_text: 'Under what specific condition does 3NF fail while BCNF succeeds?', option_a: 'When there are transitive dependencies.', option_b: 'When a non-prime attribute determines a prime attribute.', option_c: 'When there are multi-valued dependencies.', option_d: 'When all attributes are atomic.', correct_option: 'b', difficulty: 4, concept_tested: 'BCNF violation', explanation: 'BCNF is stricter than 3NF. It handles the edge case where a non-prime attribute functionally determines part of a candidate key.', prerequisite_concept: '3NF' },
  { topic_id: 8, subtopic: '1NF', question_text: 'What is the primary requirement for a relation to be in First Normal Form (1NF)?', option_a: 'No transitive dependencies', option_b: 'All attributes contain only atomic (indivisible) values', option_c: 'A primary key is explicitly defined', option_d: 'No partial dependencies', correct_option: 'b', difficulty: 1, concept_tested: '1NF atomic rule', explanation: '1NF dictates that every column must hold atomic values, meaning nested tables or comma-separated lists are not allowed.', prerequisite_concept: 'Relations basics' },

  // --- DBMS: INDEXING (Topic 9) ---
  { topic_id: 9, subtopic: 'B-Tree Index', question_text: 'Why are B-Trees preferred over Binary Search Trees (BST) for database indexing?', option_a: 'B-Trees take up less memory.', option_b: 'B-Trees naturally sort data in descending order.', option_c: 'B-Trees minimize disk I/O due to higher branching factor and shallowness.', option_d: 'BSTs cannot store primary keys.', correct_option: 'c', difficulty: 3, concept_tested: 'B-Tree disk I/O optimization', explanation: 'Databases are stored on disk. B-Trees have nodes the size of disk pages, fetching many keys in a single I/O, unlike deep BSTs.', prerequisite_concept: 'File organization' },
  { topic_id: 9, subtopic: 'Clustered vs Non-clustered', question_text: 'How many Clustered Indexes can exist on a single SQL table?', option_a: 'Zero or One', option_b: 'Exactly Two', option_c: 'Infinite', option_d: 'One per column', correct_option: 'a', difficulty: 2, concept_tested: 'Clustered index rules', explanation: 'A clustered index defines the physical sorting order of the data rows on disk. Rows can only be physically sorted one way, so there can only be one clustered index.', prerequisite_concept: 'B-Tree Index' },

  // --- DBMS: TRANSACTIONS & ACID (Topic 10) ---
  { topic_id: 10, subtopic: 'ACID Properties', question_text: "Which ACID property guarantees that a transaction is 'all or nothing'?", option_a: 'Atomicity', option_b: 'Consistency', option_c: 'Isolation', option_d: 'Durability', correct_option: 'a', difficulty: 1, concept_tested: 'Atomicity definition', explanation: 'Atomicity ensures that if any part of the transaction fails, the entire transaction is aborted and rolled back.', prerequisite_concept: 'Transaction basics' },
  { topic_id: 10, subtopic: 'Isolation Levels', question_text: "Which SQL isolation level resolves the 'Phantom Read' anomaly?", option_a: 'Read Uncommitted', option_b: 'Read Committed', option_c: 'Repeatable Read', option_d: 'Serializable', correct_option: 'd', difficulty: 5, concept_tested: 'Serializable isolation', explanation: 'Serializable is the highest isolation level, completely locking table ranges to prevent phantom inserts during the transaction.', prerequisite_concept: 'ACID Properties' },

  // --- SYSTEM DESIGN (Topics 11-13) ---
  { topic_id: 11, subtopic: 'Vertical vs Horizontal Scaling', question_text: 'Upgrading a single server with more RAM and a faster CPU is an example of:', option_a: 'Horizontal Scaling', option_b: 'Vertical Scaling', option_c: 'Load Balancing', option_d: 'Sharding', correct_option: 'b', difficulty: 1, concept_tested: 'Vertical Scaling definition', explanation: 'Vertical scaling (scaling up) involves adding more power to an existing node. Horizontal scaling (scaling out) involves adding more nodes.', prerequisite_concept: 'Basic architecture' },
  { topic_id: 11, subtopic: 'CAP Theorem', question_text: 'In the presence of a network Partition (P), CAP theorem states a distributed system must choose between:', option_a: 'Consistency and Availability', option_b: 'Consistency and Performance', option_c: 'Availability and Latency', option_d: 'Throughput and Reliability', correct_option: 'a', difficulty: 2, concept_tested: 'CAP constraints', explanation: 'During a partition, a system can either answer immediately with potentially stale data (Availability) or wait/reject until synchronized (Consistency).', prerequisite_concept: 'Basic architecture' },
  { topic_id: 12, subtopic: 'Consistent Hashing', question_text: 'What specific problem does Consistent Hashing solve in distributed systems?', option_a: 'It encrypts passwords faster.', option_b: 'It ensures a minimum of 99.9% uptime.', option_c: 'It minimizes data that needs to be re-mapped when nodes are added or removed.', option_d: 'It compresses HTTP requests.', correct_option: 'c', difficulty: 4, concept_tested: 'Consistent Hashing benefits', explanation: 'Traditional modulo hashing remaps almost everything when server count changes. Consistent hashing only re-maps a fraction k/n of keys.', prerequisite_concept: 'LB algorithms' },
  { topic_id: 13, subtopic: 'Cache Eviction Policies', question_text: 'Which cache eviction policy removes the element that has not been read or written to for the longest time?', option_a: 'LFU', option_b: 'LRU', option_c: 'FIFO', option_d: 'Random', correct_option: 'b', difficulty: 1, concept_tested: 'LRU Eviction', explanation: 'Least Recently Used (LRU) tracks the time of last access and evicts the oldest untouched item.', prerequisite_concept: 'Cache basics' },
  { topic_id: 13, subtopic: 'Write-through vs Write-back', question_text: 'What is the primary risk of a Write-back caching policy?', option_a: 'It drastically slows down read operations.', option_b: 'It causes memory fragmentation.', option_c: 'Data loss can occur if the cache crashes before the data is persisted to the database.', option_d: 'It requires more CPU cycles than Write-through.', correct_option: 'c', difficulty: 3, concept_tested: 'Write-back risk', explanation: 'In write-back, data is updated only in cache and written to DB asynchronously. A crash before the DB write results in permanent data loss.', prerequisite_concept: 'Cache basics' },

  // --- AI (Topics 14-16) ---
  { topic_id: 14, subtopic: 'Gradient Descent', question_text: 'What is the primary purpose of the learning rate in Gradient Descent?', option_a: 'To count the number of epochs.', option_b: 'To determine the step size taken towards the minimum of the loss function.', option_c: 'To calculate the final error metric.', option_d: 'To initialize the model weights.', correct_option: 'b', difficulty: 2, concept_tested: 'Learning rate function', explanation: 'The learning rate scales the gradient to dictate how drastically weights change per step. Too high = overshoot, too low = slow convergence.', prerequisite_concept: 'Cost Function' },
  { topic_id: 14, subtopic: 'Overfitting', question_text: 'Which technique is most commonly used to prevent overfitting in Linear Regression models?', option_a: 'Increasing the learning rate', option_b: 'Taking fewer samples', option_c: 'Regularization (L1/L2 Penalties)', option_d: 'Using higher cardinality data', correct_option: 'c', difficulty: 3, concept_tested: 'Regularization benefits', explanation: 'L1 (Lasso) or L2 (Ridge) Regularization adds a penalty clause to the loss function related to weight magnitudes, preventing fitting of training noise.', prerequisite_concept: 'Gradient Descent' },
  { topic_id: 15, subtopic: 'Logistic Regression', question_text: 'Despite its name, Logistic Regression is generally used for what kind of tasks?', option_a: 'Predicting continuous values', option_b: 'Dimensionality reduction', option_c: 'Clustering', option_d: 'Binary Classification', correct_option: 'd', difficulty: 1, concept_tested: 'Logistic Regression use case', explanation: 'Logistic Regression outputs probabilities squashed by a sigmoid function, making it ideal for assigning categorical classification labels.', prerequisite_concept: 'Linear Regression' },
  { topic_id: 15, subtopic: 'Confusion Matrix', question_text: 'In medical testing where falsely telling a sick patient they are healthy is catastrophic, which metric should be maximized?', option_a: 'Precision', option_b: 'Recall (Sensitivity)', option_c: 'Accuracy', option_d: 'F1 Score', correct_option: 'b', difficulty: 4, concept_tested: 'Recall vs Precision', explanation: 'Recall measures: of all actual positives, how many did we find. High recall minimizes false negatives, crucial in medical diagnosis.', prerequisite_concept: 'Evaluation Metrics' },
  { topic_id: 16, subtopic: 'Activation Functions', question_text: 'Why do Neural Networks require non-linear activation functions?', option_a: 'Because hardware only supports non-linear floats.', option_b: 'To prevent gradients from becoming too large.', option_c: 'Without them, multiple layers would collapse into a single linear transformation.', option_d: 'They restrict output values to binary 0 and 1 strictly.', correct_option: 'c', difficulty: 3, concept_tested: 'Non-linearity requirement', explanation: 'Linear functions are associative. An infinite chain of linear layers simplifies mathematically to one single linear operation.', prerequisite_concept: 'Perceptron' },
  { topic_id: 16, subtopic: 'Vanishing Gradient', question_text: 'Which activation function is most notorious for causing the vanishing gradient problem in deep networks?', option_a: 'ReLU', option_b: 'Leaky ReLU', option_c: 'Sigmoid', option_d: 'Swish', correct_option: 'c', difficulty: 3, concept_tested: 'Sigmoid saturation', explanation: 'The derivative of Sigmoid maxes out at 0.25 and approaches 0 for extreme values, causing gradients to shrink exponentially across deep layers.', prerequisite_concept: 'Activation Functions' },
];

async function seed() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query('TRUNCATE TABLE questions CASCADE');

    console.log(`Seeding ${allQuestions.length} real university-level questions...`);
    let count = 0;
    for (const q of allQuestions) {
      await client.query(
        `INSERT INTO questions (topic_id, subtopic, question_text, option_a, option_b, option_c, option_d, correct_option, difficulty, concept_tested, explanation, prerequisite_concept)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
        [q.topic_id, q.subtopic, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.difficulty, q.concept_tested, q.explanation, q.prerequisite_concept]
      );
      count++;
    }

    await client.query('COMMIT');
    console.log(`✅ Successfully inserted ${count} questions (0 dummy questions).`);
    console.log('Topic 2 (Sliding Window): 10 questions');
    console.log('Topic 4 (Dynamic Programming): 10 questions');
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Seed failed:', err.message);
  } finally {
    client.release();
    pool.end();
  }
}

seed();
